// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXZ0F8AXJBNywcv_cZOvkmWjjtoo77WkQ',
    appId: '1:468659991250:web:8bf52aeb4f62148cf0f30b',
    messagingSenderId: '468659991250',
    projectId: 'uber-tunisie-371fc',
    authDomain: 'uber-tunisie-371fc.firebaseapp.com',
    storageBucket: 'uber-tunisie-371fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6DcGYomjjkO5yP5izM37uBaVGiU1msvg',
    appId: '1:468659991250:android:2ab5d969f97b7babf0f30b',
    messagingSenderId: '468659991250',
    projectId: 'uber-tunisie-371fc',
    storageBucket: 'uber-tunisie-371fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMk1j1MwJ42X4Vri3xkPueGbrQUe3h1zQ',
    appId: '1:468659991250:ios:9182cd42c1794b04f0f30b',
    messagingSenderId: '468659991250',
    projectId: 'uber-tunisie-371fc',
    storageBucket: 'uber-tunisie-371fc.appspot.com',
    androidClientId: '468659991250-76vput1mkbgmn83n8dvch98rnc0j1dgu.apps.googleusercontent.com',
    iosClientId: '468659991250-082rmmq81vht4p3qkj0qko4jngnsifck.apps.googleusercontent.com',
    iosBundleId: 'com.example.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMk1j1MwJ42X4Vri3xkPueGbrQUe3h1zQ',
    appId: '1:468659991250:ios:9182cd42c1794b04f0f30b',
    messagingSenderId: '468659991250',
    projectId: 'uber-tunisie-371fc',
    storageBucket: 'uber-tunisie-371fc.appspot.com',
    androidClientId: '468659991250-76vput1mkbgmn83n8dvch98rnc0j1dgu.apps.googleusercontent.com',
    iosClientId: '468659991250-082rmmq81vht4p3qkj0qko4jngnsifck.apps.googleusercontent.com',
    iosBundleId: 'com.example.driver',
  );
}
